# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "jsuy"
license = "MIT"
licenselink = ""
description = ""
homepage = ""
tags = []
features = []
min_version = 0.19
[author]
  name = "Gabriel Chertok"
  homepage = "cherta.github.io"
